services:
  - type: worker
    name: hmt-stock-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python stock_checker.py
    envVars:
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
